### ISSUE TITLE
Start dev server failed on Windows - AssertionError [ERR_ASSERTION]: filePath not found of ...

### ISSUE THREAD

**Issue by imaegoo** [sorrycc/example-webpack-mfsu#1]
###  Ubuntu - success

```
mae@mae-vb:~/workspace/example-webpack-mfsu$ pnpm dev

> @ dev /home/mae/workspace/example-webpack-mfsu
> webpack-dev-server

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://10.0.2.15:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/home/mae/workspace/example-webpack-mfsu/public' directory
webpack 5.64.4 compiled successfully in 2052 ms
webpack 5.64.4 compiled successfully in 174 ms
event - [mfsu] compiled with esbuild successfully in 436 ms
```

### Windows - fail

```diff
 E:\iMaeGoo\Documents\workspace\example-webpack-mfsu>pnpm run dev
 
 > @ dev E:\iMaeGoo\Documents\workspace\example-webpack-mfsu
 > webpack-dev-server
 
 <i> [webpack-dev-server] Project is running at:
 <i> [webpack-dev-server] Loopback: http://localhost:8080/
 <i> [webpack-dev-server] On Your Network (IPv4): http://172.17.22.98:8080/
 <i> [webpack-dev-server] Content not from webpack is served from 'E:\iMaeGoo\Documents\workspace\example-webpack-mfsu\public' directory
 webpack 5.64.4 compiled successfully in 3529 ms
-error - AssertionError [ERR_ASSERTION]: filePath not found of E:iMaeGooDocumentsworkspaceexample-webpack-mfsu/src/main.tsx
-    at Dep.<anonymous> (E:\iMaeGoo\Documents\workspace\example-webpack-mfsu\node_modules\.pnpm\@umijs+mfsu@4.0.0-beta.9\node_modules\@umijs\mfsu\dist\dep\dep.js:67:34)
-    at Generator.next (<anonymous>)
-    at fulfilled (E:\iMaeGoo\Documents\workspace\example-webpack-mfsu\node_modules\.pnpm\@umijs+mfsu@4.0.0-beta.9\node_modules\@umijs\mfsu\dist\dep\dep.js:5:58)
-    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
-  generatedMessage: false,
-  code: 'ERR_ASSERTION',
-  actual: null,
-  expected: true,
-  operator: '=='
-}
 webpack 5.64.4 compiled successfully in 83 ms
```

Does not support path separator `\`.

**Comment by hasnum-stack** [comment]
+1

**Comment by sorrycc** [comment]
windows 还不支持，有兴趣来个 PR 不？
